Repository neighbortrader/FoodBoardApp, pull requests merged in 2019-10, with the labels that each got.

#72 Feature/offering information message
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/MainActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/createOffer/CreateOfferActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/createOffer/CreateOfferController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signIn/SignInActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signIn/SignInModel.java
  app/src/main/res/drawable/ic_account_circle_white_24dp.xml
  app/src/main/res/drawable/ic_add_white_24dp.xml
  app/src/main/res/drawable/ic_settings_white_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/createoffer.xml
  app/src/main/res/layout/custom_dialog2.xml
  app/src/main/res/layout/navigation_header.xml
  app/src/main/res/layout/offercardview.xml
  app/src/main/res/layout/offeroverview.xml
  app/src/main/res/layout/sign_in.xml
  app/src/main/res/menu/my_navigation_items.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/neighbortrader/foodboardapp/ExampleUnitTest.java
Labels: documentation, feature

#76 Feature/stay signed in
  app/build.gradle
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/User.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/handler/clientmodelHandler/UserHandler.java
Labels: feature

#81 created SignUp UI #75. Furthermore started with spanish translation.
  app/build.gradle
  app/src/main/res/layout/sign_in.xml
  app/src/main/res/layout/sign_up.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#82 Settings und navigation drawer update, etc.
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Address.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/User.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/handler/clientmodelHandler/UserHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/handler/clientmodelHandler/UserStatusListener.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/handler/requestsHandler/UserRequestHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/handler/tokenHandler/TokenHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/MainActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/createOffer/CreateOfferActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/mainActivity/MainActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/mainActivity/MainActivityController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/mainActivity/MainActivityModel.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerOverview/OfferOverviewController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerOverview/OfferOverviewFragment.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerOverview/OfferOverviewModel.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/settings/SettingsActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/settings/SettingsFragment.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signIn/SignInActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signIn/SignInController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signIn/SignInModel.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signUp/SignUpActivity.java
  app/src/main/res/drawable/foodbord_logo.xml
  app/src/main/res/drawable/ic_account_circle_white_24dp.xml
  app/src/main/res/drawable/ic_assignment_late_black_24dp.xml
  app/src/main/res/drawable/ic_base_url_black_24dp.xml
  app/src/main/res/drawable/ic_bug_report_black_24dp.xml
  app/src/main/res/drawable/ic_feedback_black_24dp.xml
  app/src/main/res/drawable/ic_info_outline_black_24dp.xml
  app/src/main/res/drawable/ic_local_offer_black_24dp.xml
  app/src/main/res/drawable/ic_notifications_black_24dp.xml
  app/src/main/res/font/roboto_black_italic.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/navigation_header.xml
  app/src/main/res/layout/settings_activity.xml
  app/src/main/res/layout/sign_up.xml
  app/src/main/res/menu/my_navigation_items.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/preferences.xml
  gradle.properties
Labels: Refactoring, feature

#88 Feature/about text
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature
