Repository neighbortrader/FoodBoardApp, pull requests merged in 2019-09, with the labels that each got.

#8 Feature/#1And#5
  .idea/navEditor.xml
  app/build.gradle
  app/fabric.properties
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/neighbortrader/foodboardapp/Constant.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/MainActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/MyApplication.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Address.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Groceries.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Offer.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Price.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/User.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/AsyncAllOffersRequest.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/AsyncRequest.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/OnEventListener.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/tools/ToolsFragment.java
Labels: feature

#14 Feature/request handling
  app/build.gradle
  app/src/main/java/com/github/neighbortrader/foodboardapp/Constant.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/MainActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/MyApplication.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Address.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Groceries.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Grocery.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Offer.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Price.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/ToNameValueMap.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/User.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/AsyncAllOffersRequest.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/AsyncRequest.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/CreateNewUserRequest.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/GroceryCategoryHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/OfferHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/OnEventListener.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/RequestTyps.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/UnsafeOkHttpClient.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/Urls.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/UserHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/gallery/GalleryFragment.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/home/HomeFragment.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/send/SendFragment.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/share/ShareFragment.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/slideshow/SlideshowFragment.java
  app/src/main/res/layout/app_bar_main.xml
  app/src/main/res/layout/content_main.xml
Labels: feature

#19 Feature/user handling
  README.md
  app/build.gradle
  app/src/main/java/com/github/neighbortrader/foodboardapp/MainActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Address.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Offer.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/User.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/AsyncRequest.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/CreateNewUserRequest.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/GroceryCategoryHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/OfferHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/RequestTyps.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/Urls.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/UserHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/home/HomeViewModel.java
Labels: feature

#32 Feature/post offer request
  app/build.gradle
  app/src/main/java/com/github/neighbortrader/foodboardapp/MainActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Grocery.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Offer.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/User.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/AsyncRequest.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/GroceryCategoryHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/OfferHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/OnEventListener.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/UserHandler.java
  app/src/main/res/layout/app_bar_main.xml
  app/src/main/res/layout/content_main.xml
Labels: feature

#33 impl. of Issue #29
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Offer.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/requests/OfferHandler.java
Labels: feature

#43 #27
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerDetail/OfferDetailActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerDetail/OfferDetailController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerDetail/OfferDetailModel.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/postOffer/PostOfferActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/postOffer/PostOfferController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/postOffer/PostOfferModel.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signIn/SignInActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signIn/SignInController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signIn/SignInModel.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signUp/SignUpActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signUp/SignUpController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/signUp/SignUpModel.java
Labels: Refactoring, feature

#44 Refactoring/handler
  app/src/androidTest/java/com/github/neighbortrader/foodboardapp/ExampleInstrumentedTest.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/Offer.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/clientmodel/User.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/handler/clientmodelHandler/UserHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/handler/errorHandler/ErrorHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/handler/requestsHandler/OfferRequestHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/handler/requestsHandler/UserRequestHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/handler/tokenHandler/TokenHandler.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerOverview/AllOffersController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerOverview/AllOffersModel.java
Labels: Refactoring

#60 fixed #59 and changed init process
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerOverview/AllOffersActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerOverview/AllOffersController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerOverview/AllOffersModel.java
Labels: bug

#63 added purchaseDate to createoffer.xml #47
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/createOffer/CreateOfferActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/createOffer/CreateOfferController.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/createOffer/CreateOfferModel.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/offerOverview/AllOffersActivity.java
  app/src/main/java/com/github/neighbortrader/foodboardapp/ui/postOffer/PostOfferController.java
  app/src/main/res/layout/createoffer.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug
